title: Utkarsh Raghav
email: contact@utkarshraghav.ml
description: >-
  a SDET and a Linux junkie.
baseurl: ""
url: "https://utkarshraghav.ml"
linkedin_username: utkarsh-raghav-qa
github_username:  TheCyberian

# Build settings
markdown: kramdown
theme: jekyll-swiss
theme_color: blue

plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:categories/:year/:month/:title
